[package]
name = "regex_parser"
version = "0.1.0"
edition = "2021"


[dependencies]
num-traits = "0.2.15"
regex = "1.7.0"
serde = { version = "1.0.151", features = ["derive"] }

[dev-dependencies]
regex-syntax = "0.6.28"
ron = "0.8.0"
